"""
Script to insert University of Bertoua programs into database
"""
import sys
from app.core.database import SessionLocal
from app.models.program import Program

# Programs data extracted from UBertoua PDF
bertoua_programs = [
    # FSJP - Faculte des Sciences Juridique et Politique
    {
        "code": "FSJP-DRT-PUB-L3",
        "name": "Licence en Droit Public",
        "university": "Universite de Bertoua",
        "level": "Licence",
        "department": "Faculte des Sciences Juridique et Politique",
        "description": "Formation en droit public prepara nt aux carrieres de magistrat, avocat, juriste d'entreprise, administrateur public, diplomate, enseignant-chercheur",
        "objectives": "Former des juristes specialises en droit public",
        "career_prospects": "Magistrat, avocat, juriste d'entreprise, administrateur public, diplomate, enseignant-chercheur",
        "required_bac_series": ["A", "B", "Litteraire", "GCE A/Level"],
        "min_bac_grade": None,
        "required_subjects": None,
        "riasec_match": "ESC",
        "registration_fee": 75000,
        "annual_tuition": 250000,
        "total_cost_3years": 825000,
        "employment_rate": 75,
        "average_starting_salary": 300000,
        "capacity": 100,
        "is_active": True
    },
    {
        "code": "FSJP-DRT-PRV-L3",
        "name": "Licence en Droit Prive",
        "university": "Universite de Bertoua",
        "level": "Licence",
        "department": "Faculte des Sciences Juridique et Politique",
        "description": "Formation en droit prive preparant aux carrieres juridiques",
        "objectives": "Former des juristes specialises en droit prive",
        "career_prospects": "Magistrat, avocat, juriste d'entreprise, notaire, huissier",
        "required_bac_series": ["A", "B", "Litteraire", "GCE A/Level"],
        "min_bac_grade": None,
        "required_subjects": None,
        "riasec_match": "ESC",
        "registration_fee": 75000,
        "annual_tuition": 250000,
        "total_cost_3years": 825000,
        "employment_rate": 75,
        "average_starting_salary": 300000,
        "capacity": 100,
        "is_active": True
    },
    {
        "code": "FSJP-SCI-POL-L3",
        "name": "Licence en Science Politique",
        "university": "Universite de Bertoua",
        "level": "Licence",
        "department": "Faculte des Sciences Juridique et Politique",
        "description": "Formation en sciences politiques",
        "objectives": "Former des specialistes en science politique",
        "career_prospects": "Administrateur public, diplomate, conseiller politique, enseignant-chercheur",
        "required_bac_series": ["A", "B", "Litteraire", "GCE A/Level"],
        "min_bac_grade": None,
        "required_subjects": None,
        "riasec_match": "ESC",
        "registration_fee": 75000,
        "annual_tuition": 250000,
        "total_cost_3years": 825000,
        "employment_rate": 70,
        "average_starting_salary": 280000,
        "capacity": 80,
        "is_active": True
    },

    # FALSH - Faculte des Arts, Lettres et Sciences Humaines
    {
        "code": "FALSH-GEO-L3",
        "name": "Licence en Geographie et Geomatique",
        "university": "Universite de Bertoua",
        "level": "Licence",
        "department": "Faculte des Arts, Lettres et Sciences Humaines",
        "description": "Formation en geographie et geomatique",
        "objectives": "Former des specialistes en cartographie, urbanisme et gestion de l'environnement",
        "career_prospects": "Urbaniste, Cartographe, Meteorologue, Climatologue, Geo DATA Analyst, Geomaticien, Photogrammetrie",
        "required_bac_series": ["C", "D", "E", "F", "BT"],
        "min_bac_grade": None,
        "required_subjects": None,
        "riasec_match": "IRS",
        "registration_fee": 75000,
        "annual_tuition": 250000,
        "total_cost_3years": 825000,
        "employment_rate": 80,
        "average_starting_salary": 350000,
        "capacity": 60,
        "is_active": True
    },
    {
        "code": "FALSH-HIST-L3",
        "name": "Licence en Histoire",
        "university": "Universite de Bertoua",
        "level": "Licence",
        "department": "Faculte des Arts, Lettres et Sciences Humaines",
        "description": "Formation en histoire politique, economique et sociale",
        "objectives": "Former des historiens et specialistes du patrimoine",
        "career_prospects": "Museologue, Archiviste, Antiquaire, Architecte des monuments",
        "required_bac_series": ["A", "B", "Litteraire", "GCE A/Level"],
        "min_bac_grade": None,
        "required_subjects": None,
        "riasec_match": "ISA",
        "registration_fee": 75000,
        "annual_tuition": 250000,
        "total_cost_3years": 825000,
        "employment_rate": 65,
        "average_starting_salary": 280000,
        "capacity": 50,
        "is_active": True
    },
    {
        "code": "FALSH-LEA-L3",
        "name": "Licence en Langues Etrangeres Appliquees",
        "university": "Universite de Bertoua",
        "level": "Licence",
        "department": "Faculte des Arts, Lettres et Sciences Humaines",
        "description": "Formation en langues etrangeres (Allemand, Chinois, Russe, Arabe, Espagnol)",
        "objectives": "Former des specialistes en langues etrangeres",
        "career_prospects": "Communicateurs, Interprete de voyages (affaires, touristique), Receptionniste d'hotel, Mediateurs",
        "required_bac_series": ["A", "B", "Litteraire", "GCE A/Level"],
        "min_bac_grade": None,
        "required_subjects": None,
        "riasec_match": "SAE",
        "registration_fee": 75000,
        "annual_tuition": 250000,
        "total_cost_3years": 825000,
        "employment_rate": 75,
        "average_starting_salary": 300000,
        "capacity": 70,
        "is_active": True
    },
    {
        "code": "FALSH-ANG-L3",
        "name": "Licence en English and Creative Writing",
        "university": "Universite de Bertoua",
        "level": "Licence",
        "department": "Faculte des Arts, Lettres et Sciences Humaines",
        "description": "Formation en linguistique anglaise",
        "objectives": "Former des specialistes en langue anglaise",
        "career_prospects": "Traducteur-interprete, Editeur, communicateur",
        "required_bac_series": ["A", "B", "Litteraire", "GCE A/Level"],
        "min_bac_grade": None,
        "required_subjects": None,
        "riasec_match": "ASE",
        "registration_fee": 75000,
        "annual_tuition": 250000,
        "total_cost_3years": 825000,
        "employment_rate": 75,
        "average_starting_salary": 300000,
        "capacity": 60,
        "is_active": True
    },
    {
        "code": "FALSH-FRA-L3",
        "name": "Licence en Francais et Entrepreneuriat du Livre",
        "university": "Universite de Bertoua",
        "level": "Licence",
        "department": "Faculte des Arts, Lettres et Sciences Humaines",
        "description": "Formation en litterature et langue francaise",
        "objectives": "Former des specialistes en langue et litterature francaise",
        "career_prospects": "Enseignant du superieur, Interprete, Journaliste, Romancier, Dramaturge, Poete, Critique Litteraire, Editeur, Orateur",
        "required_bac_series": ["A", "B", "Litteraire", "GCE A/Level"],
        "min_bac_grade": None,
        "required_subjects": None,
        "riasec_match": "ASE",
        "registration_fee": 75000,
        "annual_tuition": 250000,
        "total_cost_3years": 825000,
        "employment_rate": 70,
        "average_starting_salary": 280000,
        "capacity": 50,
        "is_active": True
    },

    # FS - Faculte des Sciences
    {
        "code": "FS-ENR-L3",
        "name": "Licence en Energies Renouvelables",
        "university": "Universite de Bertoua",
        "level": "Licence",
        "department": "Faculte des Sciences",
        "description": "Formation en efficacite energetique et energies renouvelables",
        "objectives": "Former des ingenieurs en energie renouvelable",
        "career_prospects": "Ingenieur en Energie renouvellable, Ingenieur de L'environnement, Enseignant, Chercheur, Technicien superieur",
        "required_bac_series": ["C", "D", "E", "F", "BT"],
        "min_bac_grade": None,
        "required_subjects": None,
        "riasec_match": "IRE",
        "registration_fee": 75000,
        "annual_tuition": 300000,
        "total_cost_3years": 975000,
        "employment_rate": 85,
        "average_starting_salary": 400000,
        "capacity": 80,
        "is_active": True
    },
    {
        "code": "FS-PHY-L3",
        "name": "Licence en Physique et Geosciences",
        "university": "Universite de Bertoua",
        "level": "Licence",
        "department": "Faculte des Sciences",
        "description": "Formation en instrumentation, metrologie, mecanique et geosciences",
        "objectives": "Former des physiciens et geoscientifiques",
        "career_prospects": "Ingenieur en Energie renouvellable, Ingenieur de L'environnement, Chimiste",
        "required_bac_series": ["C", "D", "E", "F", "BT"],
        "min_bac_grade": None,
        "required_subjects": None,
        "riasec_match": "IRE",
        "registration_fee": 75000,
        "annual_tuition": 300000,
        "total_cost_3years": 975000,
        "employment_rate": 80,
        "average_starting_salary": 380000,
        "capacity": 60,
        "is_active": True
    },
    {
        "code": "FS-CHIM-L3",
        "name": "Licence en Chimie",
        "university": "Universite de Bertoua",
        "level": "Licence",
        "department": "Faculte des Sciences",
        "description": "Formation en chimie organique, inorganique, appliquee et biochimie",
        "objectives": "Former des chimistes",
        "career_prospects": "Chimiste en industrie, laboratoire, recherche",
        "required_bac_series": ["C", "D", "E", "F", "BT"],
        "min_bac_grade": None,
        "required_subjects": None,
        "riasec_match": "IRC",
        "registration_fee": 75000,
        "annual_tuition": 300000,
        "total_cost_3years": 975000,
        "employment_rate": 80,
        "average_starting_salary": 380000,
        "capacity": 60,
        "is_active": True
    },
    {
        "code": "FS-BIO-L3",
        "name": "Licence en Biologie",
        "university": "Universite de Bertoua",
        "level": "Licence",
        "department": "Faculte des Sciences",
        "description": "Formation en biologie animale et vegetale",
        "objectives": "Former des biologistes",
        "career_prospects": "Cadre superieur dans des unites d'analyse ou de controle, de mise au point de nouveaux principes de fabrication, de recherche",
        "required_bac_series": ["C", "D", "E", "F", "BT"],
        "min_bac_grade": None,
        "required_subjects": None,
        "riasec_match": "IRC",
        "registration_fee": 75000,
        "annual_tuition": 300000,
        "total_cost_3years": 975000,
        "employment_rate": 80,
        "average_starting_salary": 350000,
        "capacity": 70,
        "is_active": True
    },
    {
        "code": "FS-MATH-L3",
        "name": "Licence en Mathematiques",
        "university": "Universite de Bertoua",
        "level": "Licence",
        "department": "Faculte des Sciences",
        "description": "Formation en mathematiques fondamentales",
        "objectives": "Former des mathematiciens",
        "career_prospects": "Securite et reseaux, Logiciels et calculs, Robotique et intelligence artificielle, Conseil finance et assurance, Environnement",
        "required_bac_series": ["C", "D", "E", "F", "BT"],
        "min_bac_grade": None,
        "required_subjects": None,
        "riasec_match": "IRC",
        "registration_fee": 75000,
        "annual_tuition": 300000,
        "total_cost_3years": 975000,
        "employment_rate": 85,
        "average_starting_salary": 400000,
        "capacity": 60,
        "is_active": True
    },
    {
        "code": "FS-STAT-L3",
        "name": "Licence en Statistiques",
        "university": "Universite de Bertoua",
        "level": "Licence",
        "department": "Faculte des Sciences",
        "description": "Formation en mathematiques, statistiques et informatique",
        "objectives": "Former des statisticiens",
        "career_prospects": "Securite et reseaux, Logiciels et calculs, Robotique et intelligence artificielle, Conseil finance et assurance",
        "required_bac_series": ["C", "D", "E", "F", "BT"],
        "min_bac_grade": None,
        "required_subjects": None,
        "riasec_match": "IRC",
        "registration_fee": 75000,
        "annual_tuition": 300000,
        "total_cost_3years": 975000,
        "employment_rate": 85,
        "average_starting_salary": 400000,
        "capacity": 50,
        "is_active": True
    },
    {
        "code": "FS-INFO-L3",
        "name": "Licence en Informatique",
        "university": "Universite de Bertoua",
        "level": "Licence",
        "department": "Faculte des Sciences",
        "description": "Formation en informatique fondamentale",
        "objectives": "Former des informaticiens",
        "career_prospects": "Securite et reseaux, Logiciels et calculs, Robotique et intelligence artificielle",
        "required_bac_series": ["C", "D", "E", "F", "BT"],
        "min_bac_grade": None,
        "required_subjects": None,
        "riasec_match": "IRC",
        "registration_fee": 75000,
        "annual_tuition": 300000,
        "total_cost_3years": 975000,
        "employment_rate": 90,
        "average_starting_salary": 450000,
        "capacity": 100,
        "is_active": True
    },
    {
        "code": "FS-BIOMED-L3",
        "name": "Licence en Sciences Biomedicales",
        "university": "Universite de Bertoua",
        "level": "Licence",
        "department": "Faculte des Sciences",
        "description": "Formation en virologie, parasitologie, microbiologie, bacteriologie, techniques d'analyses biomedicales, biochimie",
        "objectives": "Former des techniciens d'analyses biomedicales",
        "career_prospects": "Biochimiste, Bacteriologiste, Microbiologiste, Parasitologiste, Virologue, Technicien d'Analyses Biomedicales, Ingenieur Biomedicales",
        "required_bac_series": ["C", "D", "E", "F", "BT"],
        "min_bac_grade": None,
        "required_subjects": None,
        "riasec_match": "IRC",
        "registration_fee": 75000,
        "annual_tuition": 300000,
        "total_cost_3years": 975000,
        "employment_rate": 85,
        "average_starting_salary": 380000,
        "capacity": 70,
        "is_active": True
    },

    # FSEG - Faculte des Sciences Economiques et de Gestion
    {
        "code": "FSEG-BANQ-L3",
        "name": "Licence en Banque, Finance et Assurances",
        "university": "Universite de Bertoua",
        "level": "Licence",
        "department": "Faculte des Sciences Economiques et de Gestion",
        "description": "Formation en banque, finance et assurances",
        "objectives": "Former des specialistes en banque et finance",
        "career_prospects": "Analyste financier, Actuaire, Charge de Clientele, Comptable, Assistant comptable, Auditeur, Controleur de Gestion",
        "required_bac_series": ["A", "B", "C", "D", "E", "F", "Litteraire", "GCE A/Level"],
        "min_bac_grade": None,
        "required_subjects": None,
        "riasec_match": "ECS",
        "registration_fee": 75000,
        "annual_tuition": 250000,
        "total_cost_3years": 825000,
        "employment_rate": 85,
        "average_starting_salary": 400000,
        "capacity": 100,
        "is_active": True
    },
    {
        "code": "FSEG-COMPT-L3",
        "name": "Licence en Comptabilite, Controle, Audit",
        "university": "Universite de Bertoua",
        "level": "Licence",
        "department": "Faculte des Sciences Economiques et de Gestion",
        "description": "Formation en comptabilite, audit et controle",
        "objectives": "Former des comptables et auditeurs",
        "career_prospects": "Comptable, Assistant comptable, Auditeur, Controleur de Gestion",
        "required_bac_series": ["A", "B", "C", "D", "E", "F", "Litteraire", "GCE A/Level"],
        "min_bac_grade": None,
        "required_subjects": None,
        "riasec_match": "ECS",
        "registration_fee": 75000,
        "annual_tuition": 250000,
        "total_cost_3years": 825000,
        "employment_rate": 85,
        "average_starting_salary": 380000,
        "capacity": 100,
        "is_active": True
    },

    # ENS - Ecole Normale Superieure
    {
        "code": "ENS-PHYS-DIPES",
        "name": "DIPES en Physique",
        "university": "Universite de Bertoua",
        "level": "Master",
        "department": "Ecole Normale Superieure",
        "description": "Formation des professeurs de l'enseignement secondaire en Physique",
        "objectives": "Former des professeurs de physique",
        "career_prospects": "Professeur de l'Enseignement Secondaire de grades I et II, Professeur des Ecoles Normales d'Instituteurs",
        "required_bac_series": ["C", "D", "E", "F", "BT"],
        "min_bac_grade": None,
        "required_subjects": None,
        "riasec_match": "SIR",
        "registration_fee": 75000,
        "annual_tuition": 250000,
        "total_cost_3years": 575000,
        "employment_rate": 90,
        "average_starting_salary": 350000,
        "capacity": 50,
        "is_active": True
    },
    {
        "code": "ENS-MATH-DIPES",
        "name": "DIPES en Mathematiques",
        "university": "Universite de Bertoua",
        "level": "Master",
        "department": "Ecole Normale Superieure",
        "description": "Formation des professeurs de l'enseignement secondaire en Mathematiques",
        "objectives": "Former des professeurs de mathematiques",
        "career_prospects": "Professeur de l'Enseignement Secondaire de grades I et II, Professeur des Ecoles Normales d'Instituteurs",
        "required_bac_series": ["C", "D", "E", "F", "BT"],
        "min_bac_grade": None,
        "required_subjects": None,
        "riasec_match": "SIR",
        "registration_fee": 75000,
        "annual_tuition": 250000,
        "total_cost_3years": 575000,
        "employment_rate": 90,
        "average_starting_salary": 350000,
        "capacity": 50,
        "is_active": True
    },
    {
        "code": "ENS-INFO-DIPES",
        "name": "DIPES en Informatique",
        "university": "Universite de Bertoua",
        "level": "Master",
        "department": "Ecole Normale Superieure",
        "description": "Formation des professeurs de l'enseignement secondaire en Informatique",
        "objectives": "Former des professeurs d'informatique",
        "career_prospects": "Professeur de l'Enseignement Secondaire de grades I et II, Professeur des Ecoles Normales d'Instituteurs",
        "required_bac_series": ["C", "D", "E", "F", "BT"],
        "min_bac_grade": None,
        "required_subjects": None,
        "riasec_match": "SIR",
        "registration_fee": 75000,
        "annual_tuition": 250000,
        "total_cost_3years": 575000,
        "employment_rate": 90,
        "average_starting_salary": 350000,
        "capacity": 40,
        "is_active": True
    },

    # ESTM - Ecole Superieure de Transformation des Mines
    {
        "code": "ESTM-MIN-ING",
        "name": "Ingenieur en Genie Minier et Geologique",
        "university": "Universite de Bertoua",
        "level": "Ingenieur",
        "department": "Ecole Superieure de Transformation des Mines et des Ressources Energetiques",
        "description": "Formation en exploration miniere, mines et topographie miniere",
        "objectives": "Former des ingenieurs miniers",
        "career_prospects": "Ingenieur en Exploration miniere, Mineur, Topographe des mines",
        "required_bac_series": ["C", "D", "E", "F", "BT"],
        "min_bac_grade": None,
        "required_subjects": None,
        "riasec_match": "RIE",
        "registration_fee": 100000,
        "annual_tuition": 500000,
        "total_cost_3years": 2600000,
        "employment_rate": 90,
        "average_starting_salary": 600000,
        "capacity": 50,
        "is_active": True
    },
    {
        "code": "ESTM-GEM-ING",
        "name": "Ingenieur en Genie des Materiaux et Valorisation des Ressources",
        "university": "Universite de Bertoua",
        "level": "Ingenieur",
        "department": "Ecole Superieure de Transformation des Mines et des Ressources Energetiques",
        "description": "Formation en sciences des pierres precieuses et gemmologie",
        "objectives": "Former des gemmologues",
        "career_prospects": "Gemmologue",
        "required_bac_series": ["C", "D", "E", "F", "BT"],
        "min_bac_grade": None,
        "required_subjects": None,
        "riasec_match": "RIE",
        "registration_fee": 100000,
        "annual_tuition": 500000,
        "total_cost_3years": 2600000,
        "employment_rate": 85,
        "average_starting_salary": 550000,
        "capacity": 30,
        "is_active": True
    },
    {
        "code": "ESTM-ECO-ADM",
        "name": "Ingenieur en Economie et Administration Miniere",
        "university": "Universite de Bertoua",
        "level": "Ingenieur",
        "department": "Ecole Superieure de Transformation des Mines et des Ressources Energetiques",
        "description": "Formation en economie miniere et administration des entreprises minieres",
        "objectives": "Former des economistes et administrateurs miniers",
        "career_prospects": "Economiste specialise dans les mines, Administrateur des entreprises minieres, Financier des mines",
        "required_bac_series": ["C", "D", "E", "F", "BT"],
        "min_bac_grade": None,
        "required_subjects": None,
        "riasec_match": "ERI",
        "registration_fee": 100000,
        "annual_tuition": 500000,
        "total_cost_3years": 2600000,
        "employment_rate": 85,
        "average_starting_salary": 550000,
        "capacity": 40,
        "is_active": True
    },

    # ISABEE - Institut Superieur d'Agriculture
    {
        "code": "ISABEE-AGRI-ING",
        "name": "Ingenieur en Agriculture - Elevage - Aquaculture",
        "university": "Universite de Bertoua",
        "level": "Ingenieur",
        "department": "Institut Superieur d'Agriculture, du Bois, de l'eau, et de l'environnement",
        "description": "Formation en agroeconomie, aquaculture, production animale et vegetale",
        "objectives": "Former des ingenieurs agricoles",
        "career_prospects": "Chef d'exploitation Agricole, Aquaculteur, Agriculteur, Vulgarisateur Piscicole",
        "required_bac_series": ["C", "D", "E", "F", "BT"],
        "min_bac_grade": None,
        "required_subjects": None,
        "riasec_match": "RIE",
        "registration_fee": 100000,
        "annual_tuition": 400000,
        "total_cost_3years": 2300000,
        "employment_rate": 85,
        "average_starting_salary": 450000,
        "capacity": 80,
        "is_active": True
    },
    {
        "code": "ISABEE-FOR-ING",
        "name": "Ingenieur en Forets et Bois",
        "university": "Universite de Bertoua",
        "level": "Ingenieur",
        "department": "Institut Superieur d'Agriculture, du Bois, de l'eau, et de l'environnement",
        "description": "Formation en amenagement forestier, exploitation forestiere et gestion des operations forestieres",
        "objectives": "Former des ingenieurs forestiers",
        "career_prospects": "Chef de brigade d'inventaire forestier, Chef de chantier d'exploitation, Conservateur des aires protegees, Agro-forestier, Pepinieriste",
        "required_bac_series": ["C", "D", "E", "F", "BT"],
        "min_bac_grade": None,
        "required_subjects": None,
        "riasec_match": "RIE",
        "registration_fee": 100000,
        "annual_tuition": 400000,
        "total_cost_3years": 2300000,
        "employment_rate": 85,
        "average_starting_salary": 450000,
        "capacity": 60,
        "is_active": True
    },
    {
        "code": "ISABEE-ENV-ING",
        "name": "Ingenieur en Environnement",
        "university": "Universite de Bertoua",
        "level": "Ingenieur",
        "department": "Institut Superieur d'Agriculture, du Bois, de l'eau, et de l'environnement",
        "description": "Formation en changement climatique, hygiene et securite environnement",
        "objectives": "Former des ingenieurs de l'environnement",
        "career_prospects": "Ingenieur de l'environnement, specialiste en changement climatique",
        "required_bac_series": ["C", "D", "E", "F", "BT"],
        "min_bac_grade": None,
        "required_subjects": None,
        "riasec_match": "IRE",
        "registration_fee": 100000,
        "annual_tuition": 400000,
        "total_cost_3years": 2300000,
        "employment_rate": 85,
        "average_starting_salary": 450000,
        "capacity": 50,
        "is_active": True
    },

    # ESSUT - Ecole Superieure des Sciences de l'Urbanisme et du Tourisme
    {
        "code": "ESSUT-URB-ING",
        "name": "Ingenieur en Genie Urbain",
        "university": "Universite de Bertoua",
        "level": "Ingenieur",
        "department": "Ecole Superieure des Sciences de l'Urbanisme et du Tourisme",
        "description": "Formation en genie urbain, architecture urbaine et assainissement urbain",
        "objectives": "Former des ingenieurs en urbanisme",
        "career_prospects": "Ingenieur en Genie Urbain, Architecte, Urbaniste",
        "required_bac_series": ["C", "D", "E", "F", "BT"],
        "min_bac_grade": None,
        "required_subjects": None,
        "riasec_match": "RIA",
        "registration_fee": 100000,
        "annual_tuition": 450000,
        "total_cost_3years": 2450000,
        "employment_rate": 85,
        "average_starting_salary": 500000,
        "capacity": 50,
        "is_active": True
    },
    {
        "code": "ESSUT-TOUR-L3",
        "name": "Licence Professionnelle en Tourisme et Hotellerie",
        "university": "Universite de Bertoua",
        "level": "Licence",
        "department": "Ecole Superieure des Sciences de l'Urbanisme et du Tourisme",
        "description": "Formation en management touristique, gestion et management hotelier, commercialisation et services de restauration",
        "objectives": "Former des professionnels du tourisme et de l'hotellerie",
        "career_prospects": "Responsables d'agence touristique, Hote/Hotesse d'accueil, Responsable des services d'hotellerie, Maitre d'hotel",
        "required_bac_series": ["A", "B", "C", "D", "E", "F", "Litteraire", "GCE A/Level"],
        "min_bac_grade": None,
        "required_subjects": None,
        "riasec_match": "ESR",
        "registration_fee": 75000,
        "annual_tuition": 300000,
        "total_cost_3years": 975000,
        "employment_rate": 80,
        "average_starting_salary": 350000,
        "capacity": 60,
        "is_active": True
    }
]


def insert_programs():
    """Insert Bertoua programs into database"""
    db = SessionLocal()
    try:
        print(f"[INFO] Inserting {len(bertoua_programs)} programs from Universite de Bertoua...\n")

        inserted = 0
        skipped = 0

        for prog_data in bertoua_programs:
            # Check if program already exists
            existing = db.query(Program).filter(Program.code == prog_data["code"]).first()
            if existing:
                print(f"[SKIP] Program {prog_data['code']} already exists")
                skipped += 1
                continue

            # Create new program
            program = Program(**prog_data)
            db.add(program)
            inserted += 1
            print(f"[OK] Inserted: {prog_data['name']} ({prog_data['code']})")

        db.commit()
        print(f"\n[OK] Successfully inserted {inserted} programs")
        if skipped > 0:
            print(f"[INFO] Skipped {skipped} existing programs")

        # Display summary
        total_programs = db.query(Program).count()
        bertoua_count = db.query(Program).filter(
            Program.university == "Universite de Bertoua"
        ).count()
        print(f"\n[INFO] Total programs in database: {total_programs}")
        print(f"[INFO] Programs from Universite de Bertoua: {bertoua_count}")

    except Exception as e:
        print(f"[ERROR] Error inserting programs: {e}")
        db.rollback()
        import traceback
        traceback.print_exc()
    finally:
        db.close()


if __name__ == "__main__":
    insert_programs()
