"""create_initial_tables

Revision ID: 0b2866739047
Revises: 
Create Date: 2025-12-30 22:41:12.985583

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b2866739047'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('programs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('level', sa.String(length=20), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('objectives', sa.Text(), nullable=True),
    sa.Column('career_prospects', sa.Text(), nullable=True),
    sa.Column('required_bac_series', sa.JSON(), nullable=False),
    sa.Column('min_bac_grade', sa.Integer(), nullable=True),
    sa.Column('required_subjects', sa.JSON(), nullable=True),
    sa.Column('riasec_match', sa.String(length=3), nullable=False),
    sa.Column('registration_fee', sa.Integer(), nullable=False),
    sa.Column('annual_tuition', sa.Integer(), nullable=False),
    sa.Column('total_cost_3years', sa.Integer(), nullable=False),
    sa.Column('employment_rate', sa.Integer(), nullable=True),
    sa.Column('average_starting_salary', sa.Integer(), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_programs_code'), 'programs', ['code'], unique=True)
    op.create_table('riasec_dimensions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=1), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_table('activity_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activity_logs_action'), 'activity_logs', ['action'], unique=False)
    op.create_index(op.f('ix_activity_logs_created_at'), 'activity_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_activity_logs_user_id'), 'activity_logs', ['user_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('notification_type', sa.String(length=50), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('program_subjects',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('program_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('credits', sa.Integer(), nullable=False),
    sa.Column('semester', sa.Integer(), nullable=False),
    sa.Column('is_mandatory', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_program_subjects_program_id'), 'program_subjects', ['program_id'], unique=False)
    op.create_table('riasec_questions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('dimension_id', sa.String(length=36), nullable=False),
    sa.Column('question_number', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('reverse_scored', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dimension_id'], ['riasec_dimensions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('question_number')
    )
    op.create_table('student_profiles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('current_education_level', sa.String(length=50), nullable=True),
    sa.Column('bac_series', sa.String(length=20), nullable=True),
    sa.Column('bac_year', sa.Integer(), nullable=True),
    sa.Column('bac_grade', sa.Integer(), nullable=True),
    sa.Column('max_annual_budget', sa.Integer(), nullable=True),
    sa.Column('financial_aid_eligible', sa.Integer(), nullable=True),
    sa.Column('completion_percentage', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("gender IN ('M', 'F', 'Autre')", name='check_gender'),
    sa.CheckConstraint('bac_grade >= 0 AND bac_grade <= 20', name='check_bac_grade'),
    sa.CheckConstraint('completion_percentage >= 0 AND completion_percentage <= 100', name='check_completion'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('testimonials',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('program_id', sa.String(length=36), nullable=False),
    sa.Column('student_name', sa.String(length=200), nullable=False),
    sa.Column('graduation_year', sa.Integer(), nullable=False),
    sa.Column('current_position', sa.String(length=200), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('rating >= 1 AND rating <= 5', name='check_rating'),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_testimonials_program_id'), 'testimonials', ['program_id'], unique=False)
    op.create_table('academic_grades',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('subject', sa.String(length=100), nullable=False),
    sa.Column('grade', sa.Integer(), nullable=False),
    sa.Column('coefficient', sa.Integer(), nullable=False),
    sa.Column('academic_year', sa.String(length=9), nullable=False),
    sa.Column('term', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('coefficient >= 1 AND coefficient <= 10', name='check_coefficient'),
    sa.CheckConstraint('grade >= 0 AND grade <= 20', name='check_grade'),
    sa.ForeignKeyConstraint(['student_id'], ['student_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_academic_grades_student_id'), 'academic_grades', ['student_id'], unique=False)
    op.create_table('professional_values',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('autonomy', sa.Integer(), nullable=False),
    sa.Column('creativity', sa.Integer(), nullable=False),
    sa.Column('helping_others', sa.Integer(), nullable=False),
    sa.Column('job_security', sa.Integer(), nullable=False),
    sa.Column('salary', sa.Integer(), nullable=False),
    sa.Column('work_life_balance', sa.Integer(), nullable=False),
    sa.Column('prestige', sa.Integer(), nullable=False),
    sa.Column('variety', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('autonomy >= 1 AND autonomy <= 5', name='check_autonomy'),
    sa.CheckConstraint('creativity >= 1 AND creativity <= 5', name='check_creativity'),
    sa.CheckConstraint('helping_others >= 1 AND helping_others <= 5', name='check_helping_others'),
    sa.CheckConstraint('job_security >= 1 AND job_security <= 5', name='check_job_security'),
    sa.CheckConstraint('prestige >= 1 AND prestige <= 5', name='check_prestige'),
    sa.CheckConstraint('salary >= 1 AND salary <= 5', name='check_salary'),
    sa.CheckConstraint('variety >= 1 AND variety <= 5', name='check_variety'),
    sa.CheckConstraint('work_life_balance >= 1 AND work_life_balance <= 5', name='check_work_life_balance'),
    sa.ForeignKeyConstraint(['student_id'], ['student_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id')
    )
    op.create_table('recommendations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('program_id', sa.String(length=36), nullable=False),
    sa.Column('total_score', sa.Integer(), nullable=False),
    sa.Column('ranking', sa.Integer(), nullable=False),
    sa.Column('riasec_score', sa.Integer(), nullable=False),
    sa.Column('grades_score', sa.Integer(), nullable=False),
    sa.Column('values_score', sa.Integer(), nullable=False),
    sa.Column('employment_score', sa.Integer(), nullable=False),
    sa.Column('financial_score', sa.Integer(), nullable=False),
    sa.Column('strengths', sa.JSON(), nullable=True),
    sa.Column('weaknesses', sa.JSON(), nullable=True),
    sa.Column('advice', sa.Text(), nullable=True),
    sa.Column('algorithm_version', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('total_score >= 0 AND total_score <= 100', name='check_total_score'),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['student_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendations_program_id'), 'recommendations', ['program_id'], unique=False)
    op.create_index(op.f('ix_recommendations_student_id'), 'recommendations', ['student_id'], unique=False)
    op.create_table('riasec_tests',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('realistic_score', sa.Integer(), nullable=False),
    sa.Column('investigative_score', sa.Integer(), nullable=False),
    sa.Column('artistic_score', sa.Integer(), nullable=False),
    sa.Column('social_score', sa.Integer(), nullable=False),
    sa.Column('enterprising_score', sa.Integer(), nullable=False),
    sa.Column('conventional_score', sa.Integer(), nullable=False),
    sa.Column('holland_code', sa.String(length=3), nullable=False),
    sa.Column('raw_answers', sa.JSON(), nullable=False),
    sa.Column('test_version', sa.String(length=10), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('artistic_score >= 0 AND artistic_score <= 100', name='check_artistic'),
    sa.CheckConstraint('conventional_score >= 0 AND conventional_score <= 100', name='check_conventional'),
    sa.CheckConstraint('enterprising_score >= 0 AND enterprising_score <= 100', name='check_enterprising'),
    sa.CheckConstraint('investigative_score >= 0 AND investigative_score <= 100', name='check_investigative'),
    sa.CheckConstraint('realistic_score >= 0 AND realistic_score <= 100', name='check_realistic'),
    sa.CheckConstraint('social_score >= 0 AND social_score <= 100', name='check_social'),
    sa.ForeignKeyConstraint(['student_id'], ['student_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_riasec_tests_student_id'), 'riasec_tests', ['student_id'], unique=False)
    op.create_table('student_favorites',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('program_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['student_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_favorites_program_id'), 'student_favorites', ['program_id'], unique=False)
    op.create_index(op.f('ix_student_favorites_student_id'), 'student_favorites', ['student_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_student_favorites_student_id'), table_name='student_favorites')
    op.drop_index(op.f('ix_student_favorites_program_id'), table_name='student_favorites')
    op.drop_table('student_favorites')
    op.drop_index(op.f('ix_riasec_tests_student_id'), table_name='riasec_tests')
    op.drop_table('riasec_tests')
    op.drop_index(op.f('ix_recommendations_student_id'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_program_id'), table_name='recommendations')
    op.drop_table('recommendations')
    op.drop_table('professional_values')
    op.drop_index(op.f('ix_academic_grades_student_id'), table_name='academic_grades')
    op.drop_table('academic_grades')
    op.drop_index(op.f('ix_testimonials_program_id'), table_name='testimonials')
    op.drop_table('testimonials')
    op.drop_table('student_profiles')
    op.drop_table('riasec_questions')
    op.drop_index(op.f('ix_program_subjects_program_id'), table_name='program_subjects')
    op.drop_table('program_subjects')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_activity_logs_user_id'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_created_at'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_action'), table_name='activity_logs')
    op.drop_table('activity_logs')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('riasec_dimensions')
    op.drop_index(op.f('ix_programs_code'), table_name='programs')
    op.drop_table('programs')
    # ### end Alembic commands ###
